{{- $fullname := include "paperless-ngx.fullname" . }}
{{- $labels := include "paperless-ngx.labels" . }}
{{- $storageClassName := .Values.volumeStorageClassName | default "" }}
{{- range $v := .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullname }}-{{ $v.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if $storageClassName }}
  storageClassName: {{ $storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ $v.capacity }}
{{- end }}
