{{- $fullname := include "paperless-ngx.fullname" . }}
{{- $labels := include "paperless-ngx.labels" . }}
{{- range $v := .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullname }}-{{ $v.name }}
  labels:
    {{- $labels | nindent 4 }}
    app.kubernetes.io/component: {{ $v.component }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $v.storageClassName }}
  resources:
    requests:
      storage: {{ $v.capacity }}
{{- end }}
